/**
 * The CaretShader runner: one React component, authored here once, written
 * into every project that accepts a shader as `.caret/lib/CaretShader.tsx`.
 *
 * The runner is the programmatic half of the shader feature's bargain: the
 * model writes only a paint function, and everything that can be engineering
 * rather than taste — the WebGL2 dance, the fullscreen triangle, DPR capping,
 * reduced-motion, pausing offscreen, context-loss recovery, the no-WebGL
 * fallback — is written once by hand and never by a model. No three.js, no
 * dependency at all beyond React: the whole point is that a project carrying
 * a generated shader carries ~200 readable lines, not a renderer.
 *
 * Delivered as source text (the `canvas-template.ts` pattern) because it must
 * live IN the user's project to ship with it.
 *
 * Written by `generateCanvasFiles` on EVERY boot, not only at shader accept:
 * `.caret/lib/` is cleared wholesale at project open (`removeStaleShell`) so
 * an old canvas never runs against a new host — and the first live shader
 * accept proved what that does to a file written only once: the runner
 * vanished on the next launch, the component's import 500'd the shell, and
 * the chat agent hand-rolled a substitute. lib/ is derived territory;
 * user-editable shader surface is the instance component, which owns the
 * fragment and the knobs.
 */
import { SHADER_HELPERS } from "../asset-library/shader/preamble"

export const SHADER_RUNNER_VERSION = 1

const HEADER = `// caret-shader-runner v${SHADER_RUNNER_VERSION} — regenerated by Caret at every project open. Do not edit: change the shader COMPONENT (components/shaders/*.tsx), which owns the fragment and the knobs.`

export const SHADER_RUNNER_SOURCE = `${HEADER}
import { useEffect, useRef } from "react"

export type CaretShaderUniforms = Record<string, number | string | [number, number, number]>

export interface CaretShaderProps {
  /** The fragment body: one vec4 caretMain(vec2 uv) function. */
  fragment: string
  /** Knobs, by GLSL name: numbers become float uniforms, colors become vec3. */
  uniforms?: CaretShaderUniforms
  className?: string
  /** Freeze the clock. The last frame stays on screen. */
  paused?: boolean
}

const HELPERS = ${JSON.stringify(SHADER_HELPERS)}

const VERTEX_SHADER =
  "#version 300 es\\n" +
  "void main() {" +
  "  vec2 p = vec2[](vec2(-1.0, -1.0), vec2(3.0, -1.0), vec2(-1.0, 3.0))[gl_VertexID];" +
  "  gl_Position = vec4(p, 0.0, 1.0);" +
  "}"

function colorToVec3(value: string): [number, number, number] {
  const hex = /^#([0-9a-fA-F]{6})$/.exec(value)?.[1]
  if (!hex) return [0, 0, 0]
  return [parseInt(hex.slice(0, 2), 16) / 255, parseInt(hex.slice(2, 4), 16) / 255, parseInt(hex.slice(4, 6), 16) / 255]
}

function fragmentSource(fragment: string, uniforms: CaretShaderUniforms): string {
  const declarations = Object.keys(uniforms)
    .sort()
    .filter((name) => /^u_[a-z]/.test(name) && name !== "u_time" && name !== "u_resolution")
    .map((name) => "uniform " + (typeof uniforms[name] === "number" ? "float" : "vec3") + " " + name + ";")
    .join("\\n")
  return [
    "#version 300 es",
    "precision highp float;",
    "uniform float u_time;",
    "uniform vec2 u_resolution;",
    declarations,
    HELPERS,
    fragment,
    "out vec4 caretFragColor;",
    "void main() { caretFragColor = caretMain(gl_FragCoord.xy / u_resolution); }",
  ]
    .filter(Boolean)
    .join("\\n\\n")
}

export function CaretShader({ fragment, uniforms = {}, className, paused = false }: CaretShaderProps) {
  const canvasRef = useRef<HTMLCanvasElement | null>(null)
  const fallbackRef = useRef<HTMLDivElement | null>(null)
  // Uniform values reach the running loop through a ref, so tuning a knob
  // never recompiles the program — that is what makes sliders feel live.
  const uniformsRef = useRef(uniforms)
  uniformsRef.current = uniforms
  const pausedRef = useRef(paused)
  pausedRef.current = paused

  useEffect(() => {
    const canvas = canvasRef.current
    if (!canvas) return

    const gl = canvas.getContext("webgl2", { premultipliedAlpha: false })
    if (!gl) {
      // No WebGL2: show the first color knob as a flat surface instead of a
      // black hole. The poster asset is the richer fallback for static uses.
      if (fallbackRef.current) {
        const firstColor = Object.values(uniformsRef.current).find((v) => typeof v === "string")
        fallbackRef.current.style.background = typeof firstColor === "string" ? firstColor : "transparent"
      }
      return
    }

    let program: WebGLProgram | null = null
    let raf = 0
    let running = true
    let visible = true
    let disposed = false
    const started = performance.now()
    const reducedMotion = window.matchMedia("(prefers-reduced-motion: reduce)").matches

    const compile = (type: number, source: string): WebGLShader | null => {
      const shader = gl.createShader(type)
      if (!shader) return null
      gl.shaderSource(shader, source)
      gl.compileShader(shader)
      if (!gl.getShaderParameter(shader, gl.COMPILE_STATUS)) {
        console.error("[caret-shader] " + (gl.getShaderInfoLog(shader) || "compile failed"))
        gl.deleteShader(shader)
        return null
      }
      return shader
    }

    const setup = (): boolean => {
      const vertex = compile(gl.VERTEX_SHADER, VERTEX_SHADER)
      const frag = compile(gl.FRAGMENT_SHADER, fragmentSource(fragment, uniformsRef.current))
      if (!vertex || !frag) return false
      program = gl.createProgram()
      if (!program) return false
      gl.attachShader(program, vertex)
      gl.attachShader(program, frag)
      gl.linkProgram(program)
      if (!gl.getProgramParameter(program, gl.LINK_STATUS)) {
        console.error("[caret-shader] " + (gl.getProgramInfoLog(program) || "link failed"))
        return false
      }
      gl.useProgram(program)
      return true
    }

    const resize = () => {
      const ratio = Math.min(window.devicePixelRatio || 1, 2)
      const width = Math.max(1, Math.round(canvas.clientWidth * ratio))
      const height = Math.max(1, Math.round(canvas.clientHeight * ratio))
      if (canvas.width !== width || canvas.height !== height) {
        canvas.width = width
        canvas.height = height
      }
    }

    const draw = (timeSeconds: number) => {
      if (!program) return
      resize()
      gl.viewport(0, 0, canvas.width, canvas.height)
      gl.uniform1f(gl.getUniformLocation(program, "u_time"), timeSeconds)
      gl.uniform2f(gl.getUniformLocation(program, "u_resolution"), canvas.width, canvas.height)
      for (const [name, value] of Object.entries(uniformsRef.current)) {
        const location = gl.getUniformLocation(program, name)
        if (!location) continue
        if (typeof value === "number") gl.uniform1f(location, value)
        else if (typeof value === "string") gl.uniform3fv(location, colorToVec3(value))
        else gl.uniform3fv(location, value)
      }
      gl.drawArrays(gl.TRIANGLES, 0, 3)
    }

    const loop = () => {
      if (disposed) return
      if (running && visible && !pausedRef.current) draw((performance.now() - started) / 1000)
      raf = requestAnimationFrame(loop)
    }

    if (!setup()) return

    if (reducedMotion) {
      // One considered frame, then stillness — motion was declined, not the
      // gradient itself.
      draw(1.5)
    } else {
      raf = requestAnimationFrame(loop)
    }

    const observer = new IntersectionObserver((entries) => {
      visible = entries[0]?.isIntersecting !== false
    })
    observer.observe(canvas)

    const onLost = (event: Event) => {
      event.preventDefault()
      running = false
    }
    const onRestored = () => {
      if (setup()) running = true
    }
    canvas.addEventListener("webglcontextlost", onLost)
    canvas.addEventListener("webglcontextrestored", onRestored)

    return () => {
      disposed = true
      cancelAnimationFrame(raf)
      observer.disconnect()
      canvas.removeEventListener("webglcontextlost", onLost)
      canvas.removeEventListener("webglcontextrestored", onRestored)
    }
    // Recompile only when the shader itself changes; values flow via refs.
  }, [fragment, Object.keys(uniforms).sort().join(",")])

  return (
    <div ref={fallbackRef} className={className} style={{ position: "relative", overflow: "hidden" }}>
      <canvas ref={canvasRef} style={{ position: "absolute", inset: 0, width: "100%", height: "100%", display: "block" }} />
    </div>
  )
}

export default CaretShader
`

/** Whether an on-disk copy is this template or older. Absent header = user file, leave it alone. */
export function runnerVersionOf(source: string): number | null {
	const match = /^\/\/ caret-shader-runner v(\d+)/.exec(source)
	return match ? Number(match[1]) : null
}
