import * as fs from "fs/promises"
import * as path from "path"

import type { FoundationTokens } from "../types"
import { generateCanvasFiles } from "./canvas-template"
import { FONTS_CSS_FILENAME, foundationFontsCss, foundationThemeCss, THEME_CSS_FILENAME } from "./theme-css"

/**
 * (Re)generates `caret-theme.css` from the project's foundation.
 *
 * Always writes the file, even when `foundation.json` is missing or corrupt —
 * `global.css` imports it unconditionally, and a missing import takes the whole
 * shell down with a Vite internal error, which is a far worse failure than a
 * page with default styling.
 */
export async function writeThemeCss(caretDir: string): Promise<void> {
	let css = "/* GENERATED by Caret — no readable foundation.json, theme left empty. */\n"
	let fonts = "/* GENERATED by Caret — no readable foundation.json, no faces to fetch. */\n"
	try {
		const raw = await fs.readFile(path.join(caretDir, "tokens", "foundation.json"), "utf-8")
		const tokens = JSON.parse(raw) as FoundationTokens
		css = foundationThemeCss(tokens)
		fonts = `/* GENERATED by Caret from tokens/foundation.json — do not edit; edit the foundation. */\n${foundationFontsCss(tokens)}`
	} catch {
		// Scaffolding writes a default foundation before the shell starts, so this
		// is corrupt-JSON territory: keep the shell alive, let the canvas render.
	}
	await fs.writeFile(path.join(caretDir, THEME_CSS_FILENAME), css)
	await fs.writeFile(path.join(caretDir, FONTS_CSS_FILENAME), fonts)
}

/**
 * The shell's boot files, content by name. Exported (rather than inlined into
 * the writer) so the healer can compare a live file against what Caret would
 * generate and restore it the moment something else rewrites it — these files
 * ARE the Tailwind/Vite setup, and a broken one otherwise stays broken until
 * the next project open.
 */
export function entryFileSources(): Record<"index.html" | "main.tsx" | "global.css", string> {
	// index.html
	const indexHtml = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Caret Design Preview</title>
</head>
<body>
  <div id="root"></div>
  <script type="module" src="/main.tsx"></script>
</body>
</html>
`

	// main.tsx — mounts the canvas app, or a single page if ?page= is set (for iframe embedding)
	// NOTE: react-grab/styles.css must NOT be imported here. react-grab injects
	// its own styles into its shadow root at runtime; the document-level sheet
	// styles nothing but ships ~200 unlayered Tailwind-named utility classes
	// (.hidden, .block, .flex, ...) that beat the page's layered Tailwind
	// utilities in the cascade — permanently hiding any "hidden md:block"
	// responsive pattern.
	const mainTsx = `import React from "react"
import { createRoot } from "react-dom/client"
import "./global.css"

const params = new URLSearchParams(window.location.search)
const isolatedPageId = params.get("page")
const mode = params.get("mode")

// A page that error-cards is a dead document: the failed dynamic import is
// cached for the document's lifetime, and HMR propagation stops at the
// self-accepting router, so no update ever reaches this frame again. The only
// retry that actually clears the failure is a whole-document reload — so a
// dead document listens for the next design-source change (the server
// announces every one, see vite.config.ts) and reloads itself. The error
// screen disappears the moment a fix lands, in every canvas card and in the
// focused view, with no click.
let caretPageErrored = false
const markPageErrored = () => { caretPageErrored = true }
if (import.meta.hot) {
  import.meta.hot.on("caret:source-changed", () => {
    if (caretPageErrored) window.location.reload()
  })
}

// The token ripple: when new foundation tokens land over HMR, colours sweep
// (~350ms) instead of snapping — tokens are live CSS variable bindings, so a
// brief document-wide colour transition is all a sweep takes. The class is on
// only around the swap; pages carry no transition cost outside that window.
// Armed BEFORE the update applies (vite:beforeUpdate) so the swap itself is
// what transitions. global.css is matched as well as caret-theme.css because
// the theme sheet is @imported and updates arrive attributed to its importer.
const rippleStyle = document.createElement("style")
rippleStyle.textContent =
  ".caret-retheming, .caret-retheming * { transition: background-color 0.35s ease, color 0.35s ease, border-color 0.35s ease, fill 0.35s ease, stroke 0.35s ease !important; }"
document.head.appendChild(rippleStyle)
let rippleTimer = 0
if (import.meta.hot) {
  import.meta.hot.on("vite:beforeUpdate", (payload) => {
    const updates = (payload && (payload as { updates?: Array<{ path?: string }> }).updates) || []
    const themed = updates.some(u => typeof u.path === "string" && (u.path.includes("caret-theme.css") || u.path.includes("global.css")))
    if (!themed) return
    document.documentElement.classList.add("caret-retheming")
    window.clearTimeout(rippleTimer)
    rippleTimer = window.setTimeout(() => document.documentElement.classList.remove("caret-retheming"), 600)
  })
}

const escapeHtml = (s: string) =>
  s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;")

// The rejection of a failed dynamic import names the module URL, never the
// cause; the cause sits in the dev server's 500 body as an error object. One
// fetch turns "Failed to fetch dynamically imported module" into "Failed to
// resolve import 'gsap' from pages/x/index.tsx" — the difference between an
// error card (and checks feedback) an agent can act on and one it can only
// re-guess from. Falls back to the original text whenever the page's own
// module transforms fine (the failure was deeper in its import chain).
const describeLoadError = async (err: unknown): Promise<string> => {
  const text = String(err)
  if (!isolatedPageId || !/dynamically imported module|Importing a module script failed/i.test(text)) return text
  try {
    const res = await fetch("/pages/" + isolatedPageId + "/index.tsx")
    if (!res.ok) {
      const body = await res.text()
      const match = /"message":"((?:[^"\\\\]|\\\\.)*)"/.exec(body)
      if (match) return JSON.parse('"' + match[1] + '"')
    }
  } catch {}
  return text
}

// Routes carry loaders, not components — the router must stay evaluable when
// one page's imports are broken, so a page fails HERE, in its own document.
// The loader is AWAITED before anything mounts: rendering a lazy component
// instead committed an empty frame first, and everything keyed on "the frame
// has content" raced that null commit. First paint is the whole page or the
// error card, never a blank. The boundary covers the other half — a page that
// loads and then crashes at runtime — with the same card, because blank-white
// is indistinguishable from an empty page. Big type on purpose: thumbnails
// render at roughly quarter scale.
class CaretPageBoundary extends React.Component<{ children?: React.ReactNode }, { error: Error | null }> {
  state = { error: null as Error | null }
  static getDerivedStateFromError(error: Error) { markPageErrored(); return { error } }
  render() {
    if (!this.state.error) return this.props.children
    // data-caret-page-error carries the real error for machines — the design
    // checks read it and feed it back to the agent that wrote the page.
    return (
      <div data-caret-page-error={"Page crashed: " + String(this.state.error)} style={{ display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", minHeight: "100vh", padding: 48, background: "#fff5f5", color: "#b91c1c", fontFamily: "system-ui,sans-serif", textAlign: "center" }}>
        <div style={{ fontSize: 96, lineHeight: 1 }}>⚠</div>
        <div style={{ fontSize: 48, fontWeight: 700, margin: "24px 0 16px" }}>Page failed to load</div>
        <div style={{ fontSize: 26, color: "#7f1d1d", maxWidth: 900, wordBreak: "break-word" }}>{String(this.state.error)}</div>
      </div>
    )
  }
}

if (isolatedPageId && mode === "focused") {
  const flog = (msg: string) => window.parent.postMessage({ source: "caret-vite", type: "log", payload: { message: "[focused] " + msg } }, "*")
  flog("loading for page: " + isolatedPageId)
  document.body.style.background = "#ffffff"
  document.body.style.overflow = "auto"

  import("react-grab").then(() => {
    flog("react-grab loaded")
    return import("./lib/caret-grab-plugin")
  }).then(() => {
    flog("caret-grab-plugin loaded, loading remaining modules...")
    return Promise.all([
      import("virtual:caret-router"),
      import("./lib/canvas/OverlayPainter"),
      import("./lib/canvas/CaretStateContext"),
      import("./lib/bridge"),
      import("./lib/canvas/canvas.css"),
    ])
  }).then(async ([routerMod, overlayMod, stateMod, bridgeMod]) => {
    flog("all modules loaded")
    const { routes } = routerMod as any
    const { OverlayPainter } = overlayMod as any
    const { CaretStateProvider } = stateMod as any
    const { bridge } = bridgeMod as any
    flog("routes available: " + JSON.stringify(routes.map((r: any) => r.name)))
    const route = routes.find((r: any) => r.name === isolatedPageId)
    if (!route) {
      flog("ERROR: route not found for page: " + isolatedPageId)
      document.getElementById("root")!.innerHTML =
        '<div style="padding:20px;color:#f87171;font-family:monospace;font-size:13px">' +
        '<h3 style="color:#fca5a5">Route not found</h3>' +
        '<p>Page "' + isolatedPageId + '" not found in routes.</p></div>'
      return
    }
    flog("route found, loading the page module")

    // Awaited BEFORE the app mounts — see CaretPageBoundary's comment. A
    // rejection here (an unresolvable import) falls to the catch below.
    const PageComponent = (await route.loader()).default

    function FocusedApp() {
      const [paintMode, setPaintMode] = React.useState(false)
      const [currentState, setCurrentState] = React.useState("default")

      // Sample the rendered background behind the floating buttons and switch
      // them to a dark style when the page underneath is light.
      React.useEffect(() => {
        // Returns perceived lightness 0..1 + alpha. Handles rgb()/rgba() and the
        // oklch()/oklab() values Tailwind v4 emits (their first component is
        // perceptual lightness, which is exactly what we need).
        const parseLuminance = (value: string | null): { lum: number; a: number } | null => {
          if (!value) return null
          const open = value.indexOf("(")
          const close = value.lastIndexOf(")")
          if (open === -1 || close === -1) return null
          const body = value.slice(open + 1, close)
          if (value.indexOf("rgb") === 0) {
            const parts = body.split(",").map(s => parseFloat(s))
            if (parts.length < 3 || parts.slice(0, 3).some(n => isNaN(n))) return null
            return { lum: (0.2126 * parts[0] + 0.7152 * parts[1] + 0.0722 * parts[2]) / 255, a: parts.length > 3 ? parts[3] : 1 }
          }
          if (value.indexOf("oklch") === 0 || value.indexOf("oklab") === 0) {
            const slash = body.indexOf("/")
            const main = (slash === -1 ? body : body.slice(0, slash)).split(" ").filter(s => s.length > 0)
            if (main.length === 0) return null
            let l = parseFloat(main[0])
            if (main[0].indexOf("%") !== -1) l = l / 100
            if (isNaN(l)) return null
            const a = slash === -1 ? 1 : parseFloat(body.slice(slash + 1))
            return { lum: l, a: isNaN(a) ? 1 : a }
          }
          return null
        }
        // Walk the first-child chain from <body> (the elements painted at the
        // top-left, where the buttons sit) and take the deepest opaque
        // background. Hit-testing (elementsFromPoint) is useless here: active
        // react-grab puts the page content behind pointer-events: none.
        const isOwnUi = (el: Element) =>
          el.classList?.contains("caret-focused-fab") ||
          el.hasAttribute?.("data-react-grab") ||
          (typeof el.className === "string" && el.className.indexOf("caret-overlay") !== -1)
        const detect = () => {
          try {
            let found: number | null = null
            let el: HTMLElement | null = document.body
            let depth = 0
            while (el && depth < 40) {
              const c = parseLuminance(window.getComputedStyle(el).backgroundColor)
              if (c && c.a > 0.5) {
                // Only count real backdrops, not small widgets (logos, badges)
                // the first-child chain may descend into.
                const rect = el.getBoundingClientRect()
                if (el === document.body || (rect.width >= 200 && rect.height >= 200)) found = c.lum
              }
              let next: HTMLElement | null = null
              for (const child of Array.from(el.children)) {
                if (!isOwnUi(child)) { next = child as HTMLElement; break }
              }
              el = next
              depth++
            }
            if (found !== null) {
              // Toggle a class on the shell root instead of going through React
              // state: the root's className prop never changes, so React leaves
              // externally-added classes alone across re-renders.
              const shell = document.querySelector(".caret-focused")
              if (shell) shell.classList.toggle("fabs-on-light", found > 0.6)
            }
          } catch {}
        }
        detect()
        const t1 = setTimeout(detect, 400)
        const t2 = setTimeout(detect, 1500)
        let raf = 0
        const onScroll = () => {
          if (raf) return
          raf = requestAnimationFrame(() => { raf = 0; detect() })
        }
        document.addEventListener("scroll", onScroll, { passive: true, capture: true })
        if (import.meta.hot) import.meta.hot.on("vite:afterUpdate", detect)
        return () => {
          clearTimeout(t1)
          clearTimeout(t2)
          if (raf) cancelAnimationFrame(raf)
          document.removeEventListener("scroll", onScroll, { capture: true })
          if (import.meta.hot) import.meta.hot.off("vite:afterUpdate", detect)
        }
      }, [currentState])

      React.useEffect(() => {
        const filePath = "pages/" + isolatedPageId + "/index.tsx"
        ;(window as any).__CARET_FOCUSED_PAGE__ = { pageId: isolatedPageId, filePath }
        bridge.send({ type: "page-focused", payload: { filePath } })

        const hmrHandler = () => {
          bridge.send({ type: "page-focused", payload: { filePath } })
        }
        if (import.meta.hot) {
          import.meta.hot.on("vite:afterUpdate", hmrHandler)
        }

        const rg = (window as any).__REACT_GRAB__
        bridge.send({ type: "log", payload: { message: "[focused] React Grab available: " + !!rg } })
        if (rg) rg.activate()

        const msgHandler = (e: MessageEvent) => {
          if (e.data?.type === "set-state") {
            setCurrentState(e.data.value)
          }
        }
        window.addEventListener("message", msgHandler)

        return () => {
          if (rg) rg.deactivate()
          ;(window as any).__CARET_FOCUSED_PAGE__ = null
          if (import.meta.hot) import.meta.hot.off("vite:afterUpdate", hmrHandler)
          window.removeEventListener("message", msgHandler)
        }
      }, [])

      return (
        <CaretStateProvider value={currentState}>
          <div className="caret-focused">
            <button onClick={() => window.parent.postMessage({ source: "caret-page-iframe", type: "back" }, "*")} className="caret-focused-fab" title="Back to canvas">←</button>
            <button
              onClick={() => setPaintMode(!paintMode)}
              className={"caret-focused-fab caret-focused-paint-btn" + (paintMode ? " active" : "")}
              title={paintMode ? "Exit paint mode" : "Paint to edit"}
            >
              ✎
            </button>
            <button onClick={() => window.parent.postMessage({ source: "caret-page-iframe", type: "simulate" }, "*")} className="caret-focused-fab caret-focused-sim-btn" title="Simulate">▶</button>
            <div className="caret-focused-content">
              <CaretPageBoundary>
                <PageComponent />
              </CaretPageBoundary>
            </div>
            {paintMode && <OverlayPainter onClose={() => setPaintMode(false)} />}
          </div>
        </CaretStateProvider>
      )
    }

    createRoot(document.getElementById("root")!).render(<FocusedApp />)
  }).catch(async (err) => {
    flog("FAILED: " + String(err))
    markPageErrored()
    const detail = await describeLoadError(err)
    document.getElementById("root")!.innerHTML =
      '<div data-caret-page-error="' + escapeHtml(detail) + '" style="padding:20px;color:#f87171;font-family:monospace;font-size:13px">' +
      '<h3 style="color:#fca5a5">Focused mode failed to load</h3>' +
      '<pre style="white-space:pre-wrap">' + escapeHtml(detail) + '</pre></div>'
  })
} else if (isolatedPageId) {
  document.body.style.background = "#ffffff"
  document.body.style.overflow = "auto"

  // Failures must be readable inside a canvas thumbnail (scaled to ~0.26),
  // hence the very large type. A blank white box is indistinguishable from a
  // blank page and hides bad AI output.
  const showPageError = (title: string, detail: string) => {
    markPageErrored()
    document.getElementById("root")!.innerHTML =
      '<div data-caret-page-error="' + escapeHtml(title + ": " + detail) + '" style="display:flex;flex-direction:column;align-items:center;justify-content:center;min-height:100vh;padding:48px;background:#fff5f5;color:#b91c1c;font-family:system-ui,sans-serif;text-align:center">' +
      '<div style="font-size:96px;line-height:1">⚠</div>' +
      '<div style="font-size:48px;font-weight:700;margin:24px 0 16px">' + escapeHtml(title) + '</div>' +
      '<div style="font-size:26px;color:#7f1d1d;max-width:900px;word-break:break-word">' + escapeHtml(detail) + '</div>' +
      '</div>'
  }
  // Only before React owns #root: overwriting the container after mount
  // orphans React's live tree onto detached DOM, so even a later successful
  // re-render paints into nodes no longer in the document. Post-mount crashes
  // are the boundary's job; an uncaught async error still marks the document
  // dead so the next source change reloads it.
  let reactMounted = false
  window.addEventListener("error", (e) => {
    markPageErrored()
    if (!reactMounted) showPageError("Page crashed", String(e.message || e.error || "Unknown runtime error"))
  })

  import("virtual:caret-router").then(async ({ routes }: any) => {
    const route = routes.find((r: any) => r.name === isolatedPageId)
    if (!route) {
      showPageError("Page not found", "pages/" + isolatedPageId + "/index.tsx is missing or failed to compile")
      return
    }
    // Awaited before mounting, so the first paint is the page or the error
    // card — never an empty frame something else mistakes for "rendered".
    const PageComponent = (await route.loader()).default
    createRoot(document.getElementById("root")!).render(
      <CaretPageBoundary>
        <PageComponent />
      </CaretPageBoundary>
    )
    reactMounted = true
  }).catch(async (err) => {
    showPageError("Page failed to load", await describeLoadError(err))
  })
} else {
  // Canvas mode deliberately does NOT load react-grab: the editable page lives
  // in the mode=focused iframe with its own instance. A second instance here
  // overlays the canvas document, can only ever "select" the iframe, and its
  // toolbar hijacks AI-edit prompts (which carry no screenshot).
  import("./lib/canvas/CanvasApp").then(({ CanvasApp }) => {
    createRoot(document.getElementById("root")!).render(<CanvasApp />)
  })
}
`

	// global.css — Tailwind v4 + Caret overrides
	// source(none) disables Tailwind's automatic content detection, which would
	// otherwise scan the whole .caret dir — its Vite plugin then force-reloads every
	// client whenever any scanned file (e.g. flows/*.flow.json) changes.
	//
	// caret-theme.css is the foundation defined INTO Tailwind's theme: without
	// it, the `text-brand-*` classes the rules tell agents to use generate no
	// CSS at all and every page silently renders in inherited colours.
	//
	// The webfont import comes FIRST, above Tailwind's own: `@import` is only legal
	// before any other statement in the *output*, and `@import "tailwindcss"`
	// expands to the entire preflight in place. Anything importing a font after it
	// is thrown away by PostCSS and the faces never load.
	const globalCss = `@import "./caret-fonts.css";
@import "tailwindcss" source(none);
@import "./caret-theme.css";
@import "./caret-take-sources.css";

@source "./pages/**/*.{tsx,jsx}";
@source "./components/**/*.{tsx,jsx}";
@source "./layouts/**/*.{tsx,jsx}";
@source "./lib/**/*.{tsx,jsx}";

body {
  font-family: var(--caret-font-family);
  font-size: var(--caret-font-base);
  line-height: 1.5;
  color: #1f2937;
  background: #0a0a0a;
  overflow: hidden;
}
`

	return { "index.html": indexHtml, "main.tsx": mainTsx, "global.css": globalCss }
}

export async function generateEntryFiles(caretDir: string): Promise<void> {
	for (const [name, content] of Object.entries(entryFileSources())) {
		await fs.writeFile(path.join(caretDir, name), content)
	}
	await writeThemeCss(caretDir)

	// global.css imports it unconditionally; the vite plugin owns its content
	// (one @source line per open playground take — Tailwind's scanner honours
	// .gitignore, so gitignored take pages need per-file registration). Seeded
	// empty here so a boot with no exploration never 500s on a missing import;
	// NOT overwritten if present — a restart mid-exploration keeps its lines
	// until the plugin rebuilds them from the scratch.
	const takeSources = path.join(caretDir, "caret-take-sources.css")
	try {
		await fs.access(takeSources)
	} catch {
		await fs.writeFile(takeSources, "/* Generated: @source lines for open playground takes — see caret-tailwind-fresh. */\n")
	}

	// Ensure pages directory exists
	await fs.mkdir(path.join(caretDir, "pages"), { recursive: true })

	// Generate canvas component files
	await generateCanvasFiles(caretDir)
}
